export const firestoreCollections = Object.freeze({
	users: "users",
	sessions: "sessions",
	semesters: "semesters",
	subjects: "subjects",
	studyMaterials: "studyMaterials",
	papers: "papers",
	questions: "questions",
	answers: "answers",
	progress: "progress",
	notes: "notes",
	banners: "banners",
	lectures: "lectures",
	contributors: "contributors",
	discussions: "discussions",
	comments: "comments",
	appSettings: "appSettings",
	assignments: "assignments",
	reports: "reports",
	fileAssets: "fileAssets",
	auditLogs: "auditLogs",
	analyticsVisits: "analyticsVisits",
	feedback: "feedback"
});
