CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED');
CREATE TYPE "PublishStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "ReportStatus" AS ENUM ('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED');
ALTER TABLE "User" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "StudyMaterial" ADD COLUMN "status" "PublishStatus" NOT NULL DEFAULT 'PUBLISHED';
ALTER TABLE "Paper" ADD COLUMN "status" "PublishStatus" NOT NULL DEFAULT 'PUBLISHED';
CREATE TABLE "Semester" ("id" TEXT NOT NULL, "number" INTEGER NOT NULL, "title" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "status" "PublishStatus" NOT NULL DEFAULT 'PUBLISHED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Semester_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Semester_number_key" ON "Semester"("number");
CREATE TABLE "Assignment" ("id" TEXT NOT NULL, "subjectId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "dueDate" TIMESTAMP(3), "solutionUrl" TEXT, "status" "PublishStatus" NOT NULL DEFAULT 'DRAFT', "createdById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Assignment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Assignment_subjectId_status_idx" ON "Assignment"("subjectId", "status");
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "Report" ("id" TEXT NOT NULL, "reporterId" TEXT NOT NULL, "reportedUserId" TEXT, "targetType" TEXT NOT NULL, "targetId" TEXT, "reason" TEXT NOT NULL, "details" TEXT, "status" "ReportStatus" NOT NULL DEFAULT 'OPEN', "resolution" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Report_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Report_status_createdAt_idx" ON "Report"("status", "createdAt");
ALTER TABLE "Report" ADD CONSTRAINT "Report_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "FileAsset" ("id" TEXT NOT NULL, "originalName" TEXT NOT NULL, "storedName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" INTEGER NOT NULL, "path" TEXT NOT NULL, "category" TEXT NOT NULL, "uploadedById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FileAsset_pkey" PRIMARY KEY ("id"));
CREATE INDEX "FileAsset_category_createdAt_idx" ON "FileAsset"("category", "createdAt");
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "actorId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "details" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType", "entityId");
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
